[versions]
lavalink-api = "4.2.2"
lavalink-server = "4.2.2"
ktor = "3.5.2"
subsonicKotlin = "1.0.0-beta07"

[libraries]
subsonicClient = { module = "dev.zt64.subsonic:subsonic-client", version.ref = "subsonicKotlin" }
ktorClient = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorEngine = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[plugins]
lavalink = { id = "dev.arbjerg.lavalink.gradle-plugin", version = "1.1.2" }
